#!/usr/bin/env python

import csv
import sys
import os

sys.path.append('..')
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "project.settings")


from main.models import State, StateCapital, City

print os.path.abspath(__file__)

dir_name = os.path.dirname(os.path.abspath(__file__))
file_name ="cities.csv"

cities_csv = os.path.join(dir_name, file_name)

csv_file = open(cities_csv, 'r')

reader = csv.DictReader(csv_file)
